pipeline {
    agent any
    parameters {

        choice(name: 'OS', choices: ['linux', 'android', 'windows'], description: 'Pick OS')
        choice(name: 'ARCH', choices: ['386', 'arm', 'arm64', 'amd64', 'windows', 'all'], description: 'Pick ARCH')

    }
    stages {
        stage('CI') {
            steps {
                echo "Build for platform ${params.OS}"

                echo "Build for arch: ${params.ARCH}"

            }
        }
    }
}