# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "vitali-o"
  tag: "v1.0.7-2515c2d"
  os: "linux"
  arch: "amd64"
secret:
  name: "kbot"
  tokenKey: "token"
  tokenName: "TELE_TOKEN"
dnsConfig:
  nameservers: 1.1.1.1
